language: node_js

cache:
  directories:
    - node_modules

node_js:
  - "6"
  - "7"
  - "8"

env:
  - MODULE="quantum-api"
  - MODULE="quantum-changelog"
  - MODULE="quantum-code-highlight"
  - MODULE="quantum-diagram"
  - MODULE="quantum-docs"
  - MODULE="quantum-dom"
  - MODULE="quantum-html"
  - MODULE="quantum-core"
  - MODULE="quantum-template"
  - MODULE="quantum-version"
  - MODULE="cross-compatible"
  - MODULE="docs"

before_install: cd $MODULE

deploy:
  email: quantumjs.ci.noreply@ocado.com
  api_key:
    secure: GpXKIC946J3acPqCmUCMUa+/g6vHh0mSkAw0ut7HpLYUBpUnNKZGHNePevOum/jxeAjMQOSAIlUW9nWo2A9wkrx7hV7mwIhTOhIQiSqGrQ/kOyAEWNXWGgrKSlzbEyOzUVJfSfesfPgGSc2gO6JjgCFuxgi7nEMrjyUdCf5Vl7lYq6HqQtbO3wcguDtq9lYbxwZ4PoDf8bN2j2aanj/Fk9KcyqAdIrUdRmOq5U3k0BcaQg31w1iaOPr4ES3UoxN/QCa+m+5ZqBYdt2Ekms7Hb8rukneTV94XaaRT2qmdQAAZfi7X66yO/z14nlpEO3z+i5kYeutdw7KoTVNhKCmbrscTB+pJ6agGk7pZkrEAlRH3DIo9k3VPo/GeifflpUWZXvQwzfEq3iaO6XtgN63NITMcuhXqykjk+u2DSCUhyiNuwf/WYlbAJWp+vYo+fnHQGpt/jRAedVPFad+NDfbJxUXluEnMCE1ujpflyIXdab3yZFrO5Hg36xdwd2tq3vAXRm/3R39h38EMLn1DkD9O5OWY0AkbXfzLLtYydmD8JHOXD9R8yzeaudcQi3Gkqt5K1dVqmNDsjP6eaC5aMRmUqRFTqt06wmQxS8yFSQQZCJDTIPztYmfb54icFNRAklA4I2QRKd/WGQ4PtBxnLQOa8zeuAp4T61aHxNx21Znt5Ts=
  on:
    branch: master
    tags: true
    node_js: 4
    condition: $TRAVIS_TAG = $MODULE*
