language: node_js

cache:
  directories:
    - node_modules

node_js:
  - '6'
  - '7'
  - '8'

env:
  - MODULE="quantum-api"
  - MODULE="quantum-code-highlight"
  - MODULE="quantum-core"
  - MODULE="quantum-diagram"
  - MODULE="quantum-docs"
  - MODULE="quantum-dom"
  - MODULE="quantum-html"
  - MODULE="quantum-template"
  - MODULE="quantum-markdown"
  - MODULE="quantum-version"
  - MODULE="integration"
  - MODULE="docs"

before_install:
  - if [ "$MODULE" != "integration" ]; then cd "$MODULE" || return; fi

install:
  - if [ "$MODULE" != "integration" ]; then npm install; else npm run link-all && npm install; fi

script:
  - if [ "$MODULE" != "integration" ]; npm test && npm run upload-coverage; else npm test; fi

deploy:
  email: quantumjs.ci.noreply@ocado.com
  provider: npm
  api_key:
    secure: KA0wqL834Git1okwC+RHHFjaGpP+dTglZwOLMjYPkN5YoTpYVayVFBrLmuhG6uFQhprLTDKvB7UMghjjP+X3NfS6YaVnuA+aPJX/BSmyhQxvKScXL6ZCY3mQB/ISzFnr2IZSIz7yj3Ee8XyKcROiHfroWmJyQBi0E7yWQ+BgJAkb7Ne7/q3DI8TdAmdZPZjr812rT9YvEX6deIzSOdlvnLxzRpNu6dxEF3QQCJVs7Q68oGs/MJyRuI9lrT4pw+jqq8Pcogo7TGAYHvEaIce9ZDh4KTINSzHDtmEfKXMWaCerAQw/NO5fW9Xr9p6xjbNhKF0qJk56ccAQo/5EGhHjmNXASTMrBaOvGPHjaHCME2HuISx5VJ6DcTKYXg3xXALwf9gTpKkrSbkBGG/cSQWdUlquxLAqMXY6kJh5FUrz5Plv7NDrVDPf0+TZs11J1vZ3AjxylKuNZOyp1w8jP2249ibgvOm062KtAOxLVBaK1ZKEy0vbFNkQAYZX1ldZ+wiZD3F1V0CRurXjxp/QlipEwQnhlVZRHBEQrMX6U88Lb1nsEuZHf6xmAFRFDxkwOw6i+sg51gv/lt6oIb+LbiOXpgI0k3DGUXKLemH/saC6ZZGiKJ8/YHob4y2xfgFjVG7DQTbWE9SkeuQmupcDwr+ky2XS0SvR3JYAyCb4+y8v/f4=
  on:
    repo: ocadotechnology/quantumjs
    branch: master
    tags: true
    node: "6"
    condition: $TRAVIS_TAG = $MODULE*