language: node_js

cache:
  directories:
    - node_modules

node_js:
  - "6"
  - "5"
  - "4"

env:
  - MODULE="quantum-api"
  - MODULE="quantum-changelog"
  - MODULE="quantum-diagram"
  - MODULE="quantum-docs"
  - MODULE="quantum-dom"
  - MODULE="quantum-html"
  - MODULE="quantum-cli"
  - MODULE="quantum-js"
  - MODULE="quantum-template"
  - MODULE="quantum-version"
  - MODULE="quantum-watch"
  - MODULE="docs"

before_install: cd $MODULE

deploy:
  on:
    branch: master
    tags: true
    node_js: 4
    condition: $TRAVIS_TAG = $MODULE*
