language: node_js

cache:
  directories:
    - node_modules

node_js:
  - "5.5"
  - "5.4"
  - "5.3"
  - "5.2"
  - "5.1"
  - "5.0"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"

env:
  - MODULE="quantum-api"
  - MODULE="quantum-changelog"
  - MODULE="quantum-diagram"
  - MODULE="quantum-docs"
  - MODULE="quantum-dom"
  - MODULE="quantum-html"
  - MODULE="quantum-hub"
  - MODULE="quantum-js"
  - MODULE="quantum-template"
  - MODULE="quantum-version"
  - MODULE="quantum-watch"
  - MODULE="docs"

before_install: cd $MODULE

deploy:
  on:
    branch: master
    tags: true
    node_js: 4.2
    condition: $TRAVIS_TAG = $MODULE*